---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
data:
  MONGO_URL: "mongodb://mongodb:80/catalogue"
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    name: catalogue
    tier: app
spec:
  containers:
  - image: techworldwithsiva/catalogue:v2
    name: catalogue
    envFrom:
    - configMapRef:
        name: catalogue-config
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    name: catalogue
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080